/*
 * Auto-generated-style C wrapper for ../imspinner_text.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "cimspinner_config.h"
//#define SPINNER_TEXTFADE
//#define SPINNER_TEXTFADING
//#define SPINNER_TEXTUNDERLINE
//#define SPINNER_TEXTUNDERLINEDOTS
//#define SPINNER_TEXTTYPING
//#define SPINNER_TEXTSCROLL
//#define SPINNER_TEXTCOLORFILL
//#define SPINNER_TEXTSCROLLCOLORS
//#define SPINNER_TEXTCOLORCYCLE
//#define SPINNER_TEXTBOUNCE
//#define SPINNER_TEXTSPLIT
//#define SPINNER_TEXTUNDERLINESCROLL
//#define SPINNER_TEXTROLL
//#define SPINNER_TEXTCOLORFUL
//#define SPINNER_TEXTCASCADE
//#define SPINNER_TEXTCONVEYOR
//#define SPINNER_TEXTREVEAL
//#define SPINNER_TEXTWAVE
//#define SPINNER_TEXTSWEEP
//#define SPINNER_TEXTSHINE
//#define SPINNER_TEXTSCROLLSWEEP
//#define SPINNER_TEXTSPOTLIGHT
//#define SPINNER_TEXTSHAKE
//#define SPINNER_TEXTFLIP
//#define SPINNER_TEXTSPIN
//#define SPINNER_TEXTTUMBLE
//#define SPINNER_TEXTSWIRL
//#define SPINNER_TEXTROLLWAVE
//#define SPINNER_TEXTVIBRATE
//#define SPINNER_TEXTGLITCH
//#define SPINNER_TEXTBLUR
//#define SPINNER_TEXTDROPOUT
//#define SPINNER_TEXTSCANLINE
//#define SPINNER_TEXTSQUASH
//#define SPINNER_TEXTSCRAMBLE
//#define SPINNER_TEXTDECODE
//#define SPINNER_TEXTVANISH

#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#ifndef CIMSPINNER_API
  #define CIMSPINNER_API
#endif

CIMSPINNER_API void SpinnerTextFade(const char *label, float radius);
CIMSPINNER_API void SpinnerTextFadeEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextFading(const char *label, const char* text, float radius, float fsize);
CIMSPINNER_API void SpinnerTextFadingEx(const char *label, const char* text, float radius, float fsize,const ImColor color, float speed);
CIMSPINNER_API void SpinnerTextUnderline(const char *label, float radius);
CIMSPINNER_API void SpinnerTextUnderlineEx(const char *label, float radius,const ImColor color, float speed, float thickness, const char *text);
CIMSPINNER_API void SpinnerTextUnderlineDots(const char *label, float radius);
CIMSPINNER_API void SpinnerTextUnderlineDotsEx(const char *label, float radius,const ImColor color, float speed, float thickness, int dashes, const char *text);
CIMSPINNER_API void SpinnerTextTyping(const char *label, float radius);
CIMSPINNER_API void SpinnerTextTypingEx(const char *label, float radius,const ImColor color, float speed, int tail, const char *text);
CIMSPINNER_API void SpinnerTextScroll(const char *label, float radius);
CIMSPINNER_API void SpinnerTextScrollEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextColorFill(const char *label, float radius);
CIMSPINNER_API void SpinnerTextColorFillEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, int mode, const char *text);
CIMSPINNER_API void SpinnerTextScrollColors(const char *label, float radius);
CIMSPINNER_API void SpinnerTextScrollColorsEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextColorCycle(const char *label, float radius);
CIMSPINNER_API void SpinnerTextColorCycleEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextBounce(const char *label, float radius);
CIMSPINNER_API void SpinnerTextBounceEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextSplit(const char *label, float radius);
CIMSPINNER_API void SpinnerTextSplitEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text);
CIMSPINNER_API void SpinnerTextUnderlineScroll(const char *label, float radius);
CIMSPINNER_API void SpinnerTextUnderlineScrollEx(const char *label, float radius,const ImColor color, float speed, float thickness, const char *text);
CIMSPINNER_API void SpinnerTextRoll(const char *label, float radius);
CIMSPINNER_API void SpinnerTextRollEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextColorful(const char *label, float radius);
CIMSPINNER_API void SpinnerTextColorfulEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextCascade(const char *label, float radius);
CIMSPINNER_API void SpinnerTextCascadeEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextConveyor(const char *label, float radius);
CIMSPINNER_API void SpinnerTextConveyorEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextReveal(const char *label, float radius);
CIMSPINNER_API void SpinnerTextRevealEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextWave(const char *label, float radius);
CIMSPINNER_API void SpinnerTextWaveEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextSweep(const char *label, float radius);
CIMSPINNER_API void SpinnerTextSweepEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, const char *text);
CIMSPINNER_API void SpinnerTextShine(const char *label, float radius);
CIMSPINNER_API void SpinnerTextShineEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, const char *text);
CIMSPINNER_API void SpinnerTextScrollSweep(const char *label, float radius);
CIMSPINNER_API void SpinnerTextScrollSweepEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, const char *text);
CIMSPINNER_API void SpinnerTextSpotlight(const char *label, float radius);
CIMSPINNER_API void SpinnerTextSpotlightEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextShake(const char *label, float radius);
CIMSPINNER_API void SpinnerTextShakeEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text);
CIMSPINNER_API void SpinnerTextFlip(const char *label, float radius);
CIMSPINNER_API void SpinnerTextFlipEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextSpin(const char *label, float radius);
CIMSPINNER_API void SpinnerTextSpinEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextTumble(const char *label, float radius);
CIMSPINNER_API void SpinnerTextTumbleEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text);
CIMSPINNER_API void SpinnerTextSwirl(const char *label, float radius);
CIMSPINNER_API void SpinnerTextSwirlEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextRollWave(const char *label, float radius);
CIMSPINNER_API void SpinnerTextRollWaveEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextVibrate(const char *label, float radius);
CIMSPINNER_API void SpinnerTextVibrateEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextGlitch(const char *label, float radius);
CIMSPINNER_API void SpinnerTextGlitchEx(const char *label, float radius,float speed, const char *text);
CIMSPINNER_API void SpinnerTextBlur(const char *label, float radius);
CIMSPINNER_API void SpinnerTextBlurEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextDropout(const char *label, float radius);
CIMSPINNER_API void SpinnerTextDropoutEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextScanline(const char *label, float radius);
CIMSPINNER_API void SpinnerTextScanlineEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text);
CIMSPINNER_API void SpinnerTextSquash(const char *label, float radius);
CIMSPINNER_API void SpinnerTextSquashEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextScramble(const char *label, float radius);
CIMSPINNER_API void SpinnerTextScrambleEx(const char *label, float radius,const ImColor color, float speed);
CIMSPINNER_API void SpinnerTextDecode(const char *label, float radius);
CIMSPINNER_API void SpinnerTextDecodeEx(const char *label, float radius,const ImColor color, float speed, const char *text);
CIMSPINNER_API void SpinnerTextVanish(const char *label, float radius);
CIMSPINNER_API void SpinnerTextVanishEx(const char *label, float radius,const ImColor color, float speed, const char *text);
#ifdef __cplusplus
}
#endif
