/*
 * Auto-generated-style C wrapper for ../imspinner_bars.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "cimspinner_config.h"
//#define SPINNER_FADEBARS
//#define SPINNER_BARSROTATEFADE
//#define SPINNER_BARSSCALEMIDDLE
//#define SPINNER_BARCHARTSINE
//#define SPINNER_BARCHARTADVSINE
//#define SPINNER_BARCHARTADVSINEFADE
//#define SPINNER_BARCHARTRAINBOW
//#define SPINNER_FLUID
//#define SPINNER_FLUIDPOINTS
//#define SPINNER_BARSSEQPULSE
//#define SPINNER_BARSCASCADEGROW
//#define SPINNER_BARSRISE
//#define SPINNER_BARSCORNERHOP
//#define SPINNER_BARSDIAGONALGROW
//#define SPINNER_BARSBOUNCECENTER
//#define SPINNER_BARSSCALEALT
//#define SPINNER_BARSCORNERWAVE
//#define SPINNER_BARSJUMP
//#define SPINNER_BARSDOUBLEROW
//#define SPINNER_BARSSIXPULSE
//#define SPINNER_BARSSIXSTAGGER
//#define SPINNER_BARSMORPHPLUS
//#define SPINNER_BARSFLIPSIX
//#define SPINNER_BARSSWAPTRIBOTTOM
//#define SPINNER_BARSSWAPTRIZIGZAG
//#define SPINNER_BARSMORPHDIAGONAL
//#define SPINNER_BARSSLIDEDIAGONAL
//#define SPINNER_BARSCONICALTERNATE
//#define SPINNER_BARSCONICWALK
//#define SPINNER_BARSMARCHIN
//#define SPINNER_BARSMARCHDOWN
//#define SPINNER_BARSWAVESKEW
//#define SPINNER_BARSROWDROP
//#define SPINNER_BARSZIGZAGROWS
//#define SPINNER_BARSFILLCASCADE
//#define SPINNER_BARSPINGPONGROWS
//#define SPINNER_BARSWAVEROWSWIDE
//#define SPINNER_BARSGRIDFADE
//#define SPINNER_BARSGRIDSPREAD
//#define SPINNER_BARSSTRETCH
//#define SPINNER_BARSSTRETCHSEQ
//#define SPINNER_BARSBOUNCEBALL
//#define SPINNER_BARSKNOCKDOTS
//#define SPINNER_BARSSTAIRCASE
//#define SPINNER_BARSKNOCKAWAY
//#define SPINNER_BARSGATES
//#define SPINNER_BARSCAPTURE
//#define SPINNER_BARSESCAPE
//#define SPINNER_BARSDEVOUR
//#define SPINNER_BARSLIFT
//#define SPINNER_BARSGAPSLIDE
//#define SPINNER_BARSCONVERGE
//#define SPINNER_BARSSWAPENDS
//#define SPINNER_BARSRELAY
//#define SPINNER_BARSPUSH
//#define SPINNER_BARSPUSHWAVE
//#define SPINNER_BARSGATHER
//#define SPINNER_BARSSPLIT
//#define SPINNER_BARSSLOT

#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#ifndef CIMSPINNER_API
  #define CIMSPINNER_API
#endif

CIMSPINNER_API void SpinnerFadeBars(const char *label, float w);
CIMSPINNER_API void SpinnerFadeBarsEx(const char *label, float w,const ImColor color, float speed, size_t bars, bool scale);
CIMSPINNER_API void SpinnerBarsRotateFade(const char *label, float rmin, float rmax , float thickness);
CIMSPINNER_API void SpinnerBarsRotateFadeEx(const char *label, float rmin, float rmax , float thickness,const ImColor color, float speed, size_t bars);
CIMSPINNER_API void SpinnerBarsScaleMiddle(const char *label, float w);
CIMSPINNER_API void SpinnerBarsScaleMiddleEx(const char *label, float w,const ImColor color, float speed, size_t bars);
CIMSPINNER_API void SpinnerBarChartSine(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartSineEx(const char *label, float radius, float thickness, const ImColor color, float speed,int bars, int mode);
CIMSPINNER_API void SpinnerBarChartAdvSine(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartAdvSineEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerBarChartAdvSineFade(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartAdvSineFadeEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode);
CIMSPINNER_API void SpinnerBarChartRainbow(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerBarChartRainbowEx(const char *label, float radius, float thickness, const ImColor color, float speed,int bars, int mode);
CIMSPINNER_API void SpinnerFluid(const char *label, float radius, const ImColor color, float speed);
CIMSPINNER_API void SpinnerFluidEx(const char *label, float radius, const ImColor color, float speed,int bars);
CIMSPINNER_API void SpinnerFluidPoints(const char *label, float radius, float thickness, const ImColor color, float speed);
CIMSPINNER_API void SpinnerFluidPointsEx(const char *label, float radius, float thickness, const ImColor color, float speed,size_t dots, float delta);
CIMSPINNER_API void SpinnerBarsSeqPulse(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSeqPulseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsCascadeGrow(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsCascadeGrowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsRise(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsRiseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsCornerHop(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsCornerHopEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsDiagonalGrow(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsDiagonalGrowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsBounceCenter(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsBounceCenterEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsScaleAlt(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsScaleAltEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsCornerWave(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsCornerWaveEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsJump(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsJumpEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsDoubleRow(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsDoubleRowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSixPulse(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSixPulseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSixStagger(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSixStaggerEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsMorphPlus(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsMorphPlusEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsFlipSix(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsFlipSixEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSwapTriBottom(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSwapTriBottomEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSwapTriZigzag(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSwapTriZigzagEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsMorphDiagonal(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsMorphDiagonalEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSlideDiagonal(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSlideDiagonalEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsConicAlternate(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsConicAlternateEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsConicWalk(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsConicWalkEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsMarchIn(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsMarchInEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsMarchDown(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsMarchDownEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsWaveSkew(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsWaveSkewEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsRowDrop(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsRowDropEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsZigzagRows(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsZigzagRowsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsFillCascade(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsFillCascadeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsPingPongRows(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsPingPongRowsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsWaveRowsWide(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsWaveRowsWideEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsGridFade(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsGridFadeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsGridSpread(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsGridSpreadEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsStretch(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsStretchEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsStretchSeq(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsStretchSeqEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsBounceBall(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsBounceBallEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsKnockDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsKnockDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsStaircase(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsStaircaseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsKnockAway(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsKnockAwayEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsGates(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsGatesEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsCapture(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsCaptureEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsEscape(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsEscapeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsDevour(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsDevourEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsLift(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsLiftEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsGapSlide(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsGapSlideEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsConverge(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsConvergeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSwapEnds(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSwapEndsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsRelay(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsRelayEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsPush(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsPushEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsPushWave(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsPushWaveEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsGather(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsGatherEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSplit(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSplitEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerBarsSlot(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBarsSlotEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
#ifdef __cplusplus
}
#endif
