/*
 * Auto-generated-style C wrapper for ../imspinner_text.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "imspinner_text.h"
#include "cimspinner_text.h"


/* C++ definition [1]
   void Spinner::SpinnerTextFade(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTFADE
CIMSPINNER_API void SpinnerTextFade(const char *label, float radius) {
  ImSpinner::SpinnerTextFade(label, radius);
}
CIMSPINNER_API void SpinnerTextFadeEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextFade(label, radius, color, speed, text);
}
#endif

/* C++ definition [2]
   void Spinner::SpinnerTextFading(const char *label, const char* text, float radius, float fsize, const ImColor &color = white, float speed = 2.8f)
*/
#ifdef SPINNER_TEXTFADING
CIMSPINNER_API void SpinnerTextFading(const char *label, const char* text, float radius, float fsize) {
  ImSpinner::SpinnerTextFading(label, text, radius, fsize);
}
CIMSPINNER_API void SpinnerTextFadingEx(const char *label, const char* text, float radius, float fsize,const ImColor color, float speed) {
  ImSpinner::SpinnerTextFading(label, text, radius, fsize, color, speed);
}
#endif

/* C++ definition [3]
   void Spinner::SpinnerTextUnderline(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, float thickness = 3.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTUNDERLINE
CIMSPINNER_API void SpinnerTextUnderline(const char *label, float radius) {
  ImSpinner::SpinnerTextUnderline(label, radius);
}
CIMSPINNER_API void SpinnerTextUnderlineEx(const char *label, float radius,const ImColor color, float speed, float thickness, const char *text) {
  ImSpinner::SpinnerTextUnderline(label, radius, color, speed, thickness, text);
}
#endif

/* C++ definition [4]
   void Spinner::SpinnerTextUnderlineDots(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, float thickness = 3.f, int dashes = 6, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTUNDERLINEDOTS
CIMSPINNER_API void SpinnerTextUnderlineDots(const char *label, float radius) {
  ImSpinner::SpinnerTextUnderlineDots(label, radius);
}
CIMSPINNER_API void SpinnerTextUnderlineDotsEx(const char *label, float radius,const ImColor color, float speed, float thickness, int dashes, const char *text) {
  ImSpinner::SpinnerTextUnderlineDots(label, radius, color, speed, thickness, dashes, text);
}
#endif

/* C++ definition [5]
   void Spinner::SpinnerTextTyping(const char *label, float radius, const ImColor &color = white, float speed = 1.f, int tail = 3, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTTYPING
CIMSPINNER_API void SpinnerTextTyping(const char *label, float radius) {
  ImSpinner::SpinnerTextTyping(label, radius);
}
CIMSPINNER_API void SpinnerTextTypingEx(const char *label, float radius,const ImColor color, float speed, int tail, const char *text) {
  ImSpinner::SpinnerTextTyping(label, radius, color, speed, tail, text);
}
#endif

/* C++ definition [6]
   void Spinner::SpinnerTextScroll(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSCROLL
CIMSPINNER_API void SpinnerTextScroll(const char *label, float radius) {
  ImSpinner::SpinnerTextScroll(label, radius);
}
CIMSPINNER_API void SpinnerTextScrollEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextScroll(label, radius, color, speed, text);
}
#endif

/* C++ definition [7]
   void Spinner::SpinnerTextColorFill(const char *label, float radius, const ImColor &color = ImColor(0xC0, 0x29, 0x42), const ImColor &bg = white, float speed = 0.5f, int mode = 0, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTCOLORFILL
CIMSPINNER_API void SpinnerTextColorFill(const char *label, float radius) {
  ImSpinner::SpinnerTextColorFill(label, radius);
}
CIMSPINNER_API void SpinnerTextColorFillEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, int mode, const char *text) {
  ImSpinner::SpinnerTextColorFill(label, radius, color, bg, speed, mode, text);
}
#endif

/* C++ definition [8]
   void Spinner::SpinnerTextScrollColors(const char *label, float radius, const ImColor &color = white, float speed = 0.2f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSCROLLCOLORS
CIMSPINNER_API void SpinnerTextScrollColors(const char *label, float radius) {
  ImSpinner::SpinnerTextScrollColors(label, radius);
}
CIMSPINNER_API void SpinnerTextScrollColorsEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextScrollColors(label, radius, color, speed, text);
}
#endif

/* C++ definition [9]
   void Spinner::SpinnerTextColorCycle(const char *label, float radius, const ImColor &color = white, float speed = 0.2f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTCOLORCYCLE
CIMSPINNER_API void SpinnerTextColorCycle(const char *label, float radius) {
  ImSpinner::SpinnerTextColorCycle(label, radius);
}
CIMSPINNER_API void SpinnerTextColorCycleEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextColorCycle(label, radius, color, speed, text);
}
#endif

/* C++ definition [10]
   void Spinner::SpinnerTextBounce(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTBOUNCE
CIMSPINNER_API void SpinnerTextBounce(const char *label, float radius) {
  ImSpinner::SpinnerTextBounce(label, radius);
}
CIMSPINNER_API void SpinnerTextBounceEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextBounce(label, radius, color, speed, text);
}
#endif

/* C++ definition [11]
   void Spinner::SpinnerTextSplit(const char *label, float radius, const ImColor &color = white, float speed = 1.f, int mode = 0, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSPLIT
CIMSPINNER_API void SpinnerTextSplit(const char *label, float radius) {
  ImSpinner::SpinnerTextSplit(label, radius);
}
CIMSPINNER_API void SpinnerTextSplitEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text) {
  ImSpinner::SpinnerTextSplit(label, radius, color, speed, mode, text);
}
#endif

/* C++ definition [12]
   void Spinner::SpinnerTextUnderlineScroll(const char *label, float radius, const ImColor &color = white, float speed = 0.66f, float thickness = 3.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTUNDERLINESCROLL
CIMSPINNER_API void SpinnerTextUnderlineScroll(const char *label, float radius) {
  ImSpinner::SpinnerTextUnderlineScroll(label, radius);
}
CIMSPINNER_API void SpinnerTextUnderlineScrollEx(const char *label, float radius,const ImColor color, float speed, float thickness, const char *text) {
  ImSpinner::SpinnerTextUnderlineScroll(label, radius, color, speed, thickness, text);
}
#endif

/* C++ definition [13]
   void Spinner::SpinnerTextRoll(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTROLL
CIMSPINNER_API void SpinnerTextRoll(const char *label, float radius) {
  ImSpinner::SpinnerTextRoll(label, radius);
}
CIMSPINNER_API void SpinnerTextRollEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextRoll(label, radius, color, speed, text);
}
#endif

/* C++ definition [14]
   void Spinner::SpinnerTextColorful(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTCOLORFUL
CIMSPINNER_API void SpinnerTextColorful(const char *label, float radius) {
  ImSpinner::SpinnerTextColorful(label, radius);
}
CIMSPINNER_API void SpinnerTextColorfulEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextColorful(label, radius, color, speed, text);
}
#endif

/* C++ definition [15]
   void Spinner::SpinnerTextCascade(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTCASCADE
CIMSPINNER_API void SpinnerTextCascade(const char *label, float radius) {
  ImSpinner::SpinnerTextCascade(label, radius);
}
CIMSPINNER_API void SpinnerTextCascadeEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextCascade(label, radius, color, speed, text);
}
#endif

/* C++ definition [16]
   void Spinner::SpinnerTextConveyor(const char *label, float radius, const ImColor &color = white, float speed = 0.33f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTCONVEYOR
CIMSPINNER_API void SpinnerTextConveyor(const char *label, float radius) {
  ImSpinner::SpinnerTextConveyor(label, radius);
}
CIMSPINNER_API void SpinnerTextConveyorEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextConveyor(label, radius, color, speed, text);
}
#endif

/* C++ definition [17]
   void Spinner::SpinnerTextReveal(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTREVEAL
CIMSPINNER_API void SpinnerTextReveal(const char *label, float radius) {
  ImSpinner::SpinnerTextReveal(label, radius);
}
CIMSPINNER_API void SpinnerTextRevealEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextReveal(label, radius, color, speed, text);
}
#endif

/* C++ definition [18]
   void Spinner::SpinnerTextWave(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTWAVE
CIMSPINNER_API void SpinnerTextWave(const char *label, float radius) {
  ImSpinner::SpinnerTextWave(label, radius);
}
CIMSPINNER_API void SpinnerTextWaveEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextWave(label, radius, color, speed, text);
}
#endif

/* C++ definition [19]
   void Spinner::SpinnerTextSweep(const char *label, float radius, const ImColor &color = white, const ImColor &bg = ImColor(0, 0, 0), float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSWEEP
CIMSPINNER_API void SpinnerTextSweep(const char *label, float radius) {
  ImSpinner::SpinnerTextSweep(label, radius);
}
CIMSPINNER_API void SpinnerTextSweepEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, const char *text) {
  ImSpinner::SpinnerTextSweep(label, radius, color, bg, speed, text);
}
#endif

/* C++ definition [20]
   void Spinner::SpinnerTextShine(const char *label, float radius, const ImColor &color = white, const ImColor &bg = ImColor(0, 0, 0), float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSHINE
CIMSPINNER_API void SpinnerTextShine(const char *label, float radius) {
  ImSpinner::SpinnerTextShine(label, radius);
}
CIMSPINNER_API void SpinnerTextShineEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, const char *text) {
  ImSpinner::SpinnerTextShine(label, radius, color, bg, speed, text);
}
#endif

/* C++ definition [21]
   void Spinner::SpinnerTextScrollSweep(const char *label, float radius, const ImColor &color = white, const ImColor &bg = ImColor(0, 0, 0), float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSCROLLSWEEP
CIMSPINNER_API void SpinnerTextScrollSweep(const char *label, float radius) {
  ImSpinner::SpinnerTextScrollSweep(label, radius);
}
CIMSPINNER_API void SpinnerTextScrollSweepEx(const char *label, float radius,const ImColor color, const ImColor bg, float speed, const char *text) {
  ImSpinner::SpinnerTextScrollSweep(label, radius, color, bg, speed, text);
}
#endif

/* C++ definition [22]
   void Spinner::SpinnerTextSpotlight(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSPOTLIGHT
CIMSPINNER_API void SpinnerTextSpotlight(const char *label, float radius) {
  ImSpinner::SpinnerTextSpotlight(label, radius);
}
CIMSPINNER_API void SpinnerTextSpotlightEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextSpotlight(label, radius, color, speed, text);
}
#endif

/* C++ definition [23]
   void Spinner::SpinnerTextShake(const char *label, float radius, const ImColor &color = white, float speed = 1.f, int mode = 0, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSHAKE
CIMSPINNER_API void SpinnerTextShake(const char *label, float radius) {
  ImSpinner::SpinnerTextShake(label, radius);
}
CIMSPINNER_API void SpinnerTextShakeEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text) {
  ImSpinner::SpinnerTextShake(label, radius, color, speed, mode, text);
}
#endif

/* C++ definition [24]
   void Spinner::SpinnerTextFlip(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTFLIP
CIMSPINNER_API void SpinnerTextFlip(const char *label, float radius) {
  ImSpinner::SpinnerTextFlip(label, radius);
}
CIMSPINNER_API void SpinnerTextFlipEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextFlip(label, radius, color, speed, text);
}
#endif

/* C++ definition [25]
   void Spinner::SpinnerTextSpin(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSPIN
CIMSPINNER_API void SpinnerTextSpin(const char *label, float radius) {
  ImSpinner::SpinnerTextSpin(label, radius);
}
CIMSPINNER_API void SpinnerTextSpinEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextSpin(label, radius, color, speed, text);
}
#endif

/* C++ definition [26]
   void Spinner::SpinnerTextTumble(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, int mode = 0, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTTUMBLE
CIMSPINNER_API void SpinnerTextTumble(const char *label, float radius) {
  ImSpinner::SpinnerTextTumble(label, radius);
}
CIMSPINNER_API void SpinnerTextTumbleEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text) {
  ImSpinner::SpinnerTextTumble(label, radius, color, speed, mode, text);
}
#endif

/* C++ definition [27]
   void Spinner::SpinnerTextSwirl(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSWIRL
CIMSPINNER_API void SpinnerTextSwirl(const char *label, float radius) {
  ImSpinner::SpinnerTextSwirl(label, radius);
}
CIMSPINNER_API void SpinnerTextSwirlEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextSwirl(label, radius, color, speed, text);
}
#endif

/* C++ definition [28]
   void Spinner::SpinnerTextRollWave(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTROLLWAVE
CIMSPINNER_API void SpinnerTextRollWave(const char *label, float radius) {
  ImSpinner::SpinnerTextRollWave(label, radius);
}
CIMSPINNER_API void SpinnerTextRollWaveEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextRollWave(label, radius, color, speed, text);
}
#endif

/* C++ definition [29]
   void Spinner::SpinnerTextVibrate(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTVIBRATE
CIMSPINNER_API void SpinnerTextVibrate(const char *label, float radius) {
  ImSpinner::SpinnerTextVibrate(label, radius);
}
CIMSPINNER_API void SpinnerTextVibrateEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextVibrate(label, radius, color, speed, text);
}
#endif

/* C++ definition [30]
   void Spinner::SpinnerTextGlitch(const char *label, float radius, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTGLITCH
CIMSPINNER_API void SpinnerTextGlitch(const char *label, float radius) {
  ImSpinner::SpinnerTextGlitch(label, radius);
}
CIMSPINNER_API void SpinnerTextGlitchEx(const char *label, float radius,float speed, const char *text) {
  ImSpinner::SpinnerTextGlitch(label, radius, speed, text);
}
#endif

/* C++ definition [31]
   void Spinner::SpinnerTextBlur(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTBLUR
CIMSPINNER_API void SpinnerTextBlur(const char *label, float radius) {
  ImSpinner::SpinnerTextBlur(label, radius);
}
CIMSPINNER_API void SpinnerTextBlurEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextBlur(label, radius, color, speed, text);
}
#endif

/* C++ definition [32]
   void Spinner::SpinnerTextDropout(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTDROPOUT
CIMSPINNER_API void SpinnerTextDropout(const char *label, float radius) {
  ImSpinner::SpinnerTextDropout(label, radius);
}
CIMSPINNER_API void SpinnerTextDropoutEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextDropout(label, radius, color, speed, text);
}
#endif

/* C++ definition [33]
   void Spinner::SpinnerTextScanline(const char *label, float radius, const ImColor &color = white, float speed = 1.f, int mode = 0, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSCANLINE
CIMSPINNER_API void SpinnerTextScanline(const char *label, float radius) {
  ImSpinner::SpinnerTextScanline(label, radius);
}
CIMSPINNER_API void SpinnerTextScanlineEx(const char *label, float radius,const ImColor color, float speed, int mode, const char *text) {
  ImSpinner::SpinnerTextScanline(label, radius, color, speed, mode, text);
}
#endif

/* C++ definition [34]
   void Spinner::SpinnerTextSquash(const char *label, float radius, const ImColor &color = white, float speed = 1.f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTSQUASH
CIMSPINNER_API void SpinnerTextSquash(const char *label, float radius) {
  ImSpinner::SpinnerTextSquash(label, radius);
}
CIMSPINNER_API void SpinnerTextSquashEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextSquash(label, radius, color, speed, text);
}
#endif

/* C++ definition [35]
   void Spinner::SpinnerTextScramble(const char *label, float radius, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_TEXTSCRAMBLE
CIMSPINNER_API void SpinnerTextScramble(const char *label, float radius) {
  ImSpinner::SpinnerTextScramble(label, radius);
}
CIMSPINNER_API void SpinnerTextScrambleEx(const char *label, float radius,const ImColor color, float speed) {
  ImSpinner::SpinnerTextScramble(label, radius, color, speed);
}
#endif

/* C++ definition [36]
   void Spinner::SpinnerTextDecode(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTDECODE
CIMSPINNER_API void SpinnerTextDecode(const char *label, float radius) {
  ImSpinner::SpinnerTextDecode(label, radius);
}
CIMSPINNER_API void SpinnerTextDecodeEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextDecode(label, radius, color, speed, text);
}
#endif

/* C++ definition [37]
   void Spinner::SpinnerTextVanish(const char *label, float radius, const ImColor &color = white, float speed = 0.5f, const char *text = "Loading...")
*/
#ifdef SPINNER_TEXTVANISH
CIMSPINNER_API void SpinnerTextVanish(const char *label, float radius) {
  ImSpinner::SpinnerTextVanish(label, radius);
}
CIMSPINNER_API void SpinnerTextVanishEx(const char *label, float radius,const ImColor color, float speed, const char *text) {
  ImSpinner::SpinnerTextVanish(label, radius, color, speed, text);
}
#endif
