/*
 * Auto-generated-style C wrapper for ../imspinner_shapes.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "imspinner_shapes.h"
#include "cimspinner_shapes.h"


/* C++ definition [1]
   void Spinner::SpinnerMorphShape(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_MORPHSHAPE
CIMSPINNER_API void SpinnerMorphShape(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerMorphShape(label, radius, thickness);
}
CIMSPINNER_API void SpinnerMorphShapeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerMorphShape(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [2]
   void Spinner::SpinnerFlipTriangle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_FLIPTRIANGLE
CIMSPINNER_API void SpinnerFlipTriangle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerFlipTriangle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerFlipTriangleEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerFlipTriangle(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [3]
   void Spinner::SpinnerFoldSquare(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_FOLDSQUARE
CIMSPINNER_API void SpinnerFoldSquare(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerFoldSquare(label, radius, thickness);
}
CIMSPINNER_API void SpinnerFoldSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerFoldSquare(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [4]
   void Spinner::SpinnerPinwheel(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_PINWHEEL
CIMSPINNER_API void SpinnerPinwheel(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerPinwheel(label, radius, thickness);
}
CIMSPINNER_API void SpinnerPinwheelEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerPinwheel(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [5]
   void Spinner::SpinnerCornerSquares(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_CORNERSQUARES
CIMSPINNER_API void SpinnerCornerSquares(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerCornerSquares(label, radius, thickness);
}
CIMSPINNER_API void SpinnerCornerSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerCornerSquares(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [6]
   void Spinner::SpinnerSplitSquare(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_SPLITSQUARE
CIMSPINNER_API void SpinnerSplitSquare(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSplitSquare(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSplitSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerSplitSquare(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [7]
   void Spinner::SpinnerCornerBurst(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_CORNERBURST
CIMSPINNER_API void SpinnerCornerBurst(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerCornerBurst(label, radius, thickness);
}
CIMSPINNER_API void SpinnerCornerBurstEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerCornerBurst(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [8]
   void Spinner::SpinnerSkewSquare(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_SKEWSQUARE
CIMSPINNER_API void SpinnerSkewSquare(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSkewSquare(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSkewSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerSkewSquare(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [9]
   void Spinner::SpinnerTumbleSquare(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_TUMBLESQUARE
CIMSPINNER_API void SpinnerTumbleSquare(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerTumbleSquare(label, radius, thickness);
}
CIMSPINNER_API void SpinnerTumbleSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerTumbleSquare(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [10]
   void Spinner::SpinnerTriDiamond(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_TRIDIAMOND
CIMSPINNER_API void SpinnerTriDiamond(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerTriDiamond(label, radius, thickness);
}
CIMSPINNER_API void SpinnerTriDiamondEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerTriDiamond(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [11]
   void Spinner::SpinnerTwinBlades(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_TWINBLADES
CIMSPINNER_API void SpinnerTwinBlades(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerTwinBlades(label, radius, thickness);
}
CIMSPINNER_API void SpinnerTwinBladesEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerTwinBlades(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [12]
   void Spinner::SpinnerCrossBlades(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_CROSSBLADES
CIMSPINNER_API void SpinnerCrossBlades(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerCrossBlades(label, radius, thickness);
}
CIMSPINNER_API void SpinnerCrossBladesEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerCrossBlades(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [13]
   void Spinner::SpinnerDriftSquare(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_DRIFTSQUARE
CIMSPINNER_API void SpinnerDriftSquare(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDriftSquare(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDriftSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerDriftSquare(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [14]
   void Spinner::SpinnerPieBounce(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_PIEBOUNCE
CIMSPINNER_API void SpinnerPieBounce(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerPieBounce(label, radius, thickness);
}
CIMSPINNER_API void SpinnerPieBounceEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerPieBounce(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [15]
   void Spinner::SpinnerLeapFrog(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_LEAPFROG
CIMSPINNER_API void SpinnerLeapFrog(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerLeapFrog(label, radius, thickness);
}
CIMSPINNER_API void SpinnerLeapFrogEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerLeapFrog(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [16]
   void Spinner::SpinnerPlusSquares(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_PLUSSQUARES
CIMSPINNER_API void SpinnerPlusSquares(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerPlusSquares(label, radius, thickness);
}
CIMSPINNER_API void SpinnerPlusSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerPlusSquares(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [17]
   void Spinner::SpinnerSevenMarch(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_SEVENMARCH
CIMSPINNER_API void SpinnerSevenMarch(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSevenMarch(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSevenMarchEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerSevenMarch(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [18]
   void Spinner::SpinnerCornerArcs(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_CORNERARCS
CIMSPINNER_API void SpinnerCornerArcs(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerCornerArcs(label, radius, thickness);
}
CIMSPINNER_API void SpinnerCornerArcsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerCornerArcs(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [19]
   void Spinner::SpinnerWalkBlocks(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_WALKBLOCKS
CIMSPINNER_API void SpinnerWalkBlocks(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerWalkBlocks(label, radius, thickness);
}
CIMSPINNER_API void SpinnerWalkBlocksEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerWalkBlocks(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [20]
   void Spinner::SpinnerTumbleHalfDisc(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_TUMBLEHALFDISC
CIMSPINNER_API void SpinnerTumbleHalfDisc(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerTumbleHalfDisc(label, radius, thickness);
}
CIMSPINNER_API void SpinnerTumbleHalfDiscEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerTumbleHalfDisc(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [21]
   void Spinner::SpinnerFoldHalfDisc(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_FOLDHALFDISC
CIMSPINNER_API void SpinnerFoldHalfDisc(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerFoldHalfDisc(label, radius, thickness);
}
CIMSPINNER_API void SpinnerFoldHalfDiscEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerFoldHalfDisc(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [22]
   void Spinner::SpinnerWiperArrow(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_WIPERARROW
CIMSPINNER_API void SpinnerWiperArrow(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerWiperArrow(label, radius, thickness);
}
CIMSPINNER_API void SpinnerWiperArrowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerWiperArrow(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [23]
   void Spinner::SpinnerSkewSquares(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_SKEWSQUARES
CIMSPINNER_API void SpinnerSkewSquares(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSkewSquares(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSkewSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerSkewSquares(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [24]
   void Spinner::SpinnerStretchSquares(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_STRETCHSQUARES
CIMSPINNER_API void SpinnerStretchSquares(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerStretchSquares(label, radius, thickness);
}
CIMSPINNER_API void SpinnerStretchSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerStretchSquares(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [25]
   void Spinner::SpinnerTriPie(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_TRIPIE
CIMSPINNER_API void SpinnerTriPie(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerTriPie(label, radius, thickness);
}
CIMSPINNER_API void SpinnerTriPieEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerTriPie(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [26]
   void Spinner::SpinnerShuffleBars(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_SHUFFLEBARS
CIMSPINNER_API void SpinnerShuffleBars(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerShuffleBars(label, radius, thickness);
}
CIMSPINNER_API void SpinnerShuffleBarsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerShuffleBars(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [27]
   void Spinner::SpinnerHingeTumble(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_HINGETUMBLE
CIMSPINNER_API void SpinnerHingeTumble(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerHingeTumble(label, radius, thickness);
}
CIMSPINNER_API void SpinnerHingeTumbleEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerHingeTumble(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [28]
   void Spinner::SpinnerDiagonalFlip(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_DIAGONALFLIP
CIMSPINNER_API void SpinnerDiagonalFlip(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDiagonalFlip(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDiagonalFlipEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerDiagonalFlip(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [29]
   void Spinner::SpinnerPulseGrid(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_PULSEGRID
CIMSPINNER_API void SpinnerPulseGrid(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerPulseGrid(label, radius, thickness);
}
CIMSPINNER_API void SpinnerPulseGridEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerPulseGrid(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [30]
   void Spinner::SpinnerMarchGrid(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_MARCHGRID
CIMSPINNER_API void SpinnerMarchGrid(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerMarchGrid(label, radius, thickness);
}
CIMSPINNER_API void SpinnerMarchGridEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerMarchGrid(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [31]
   void Spinner::SpinnerSpinBars(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_SPINBARS
CIMSPINNER_API void SpinnerSpinBars(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSpinBars(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSpinBarsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerSpinBars(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [32]
   void Spinner::SpinnerMorphDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_MORPHDOTS
CIMSPINNER_API void SpinnerMorphDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerMorphDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerMorphDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerMorphDots(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [33]
   void Spinner::SpinnerCombDiscs(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_COMBDISCS
CIMSPINNER_API void SpinnerCombDiscs(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerCombDiscs(label, radius, thickness);
}
CIMSPINNER_API void SpinnerCombDiscsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerCombDiscs(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [34]
   void Spinner::SpinnerOrbitDisc(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_ORBITDISC
CIMSPINNER_API void SpinnerOrbitDisc(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerOrbitDisc(label, radius, thickness);
}
CIMSPINNER_API void SpinnerOrbitDiscEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerOrbitDisc(label, radius, thickness, color, speed, mode);
}
#endif
