/*
 * Auto-generated-style C wrapper for ../imspinner_dots.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "imspinner_dots.h"
#include "cimspinner_dots.h"


/* C++ definition [1]
   void Spinner::SpinnerBounceDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 3, int mode = 0)
*/
#ifdef SPINNER_BOUNCEDOTS
CIMSPINNER_API void SpinnerBounceDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBounceDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBounceDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, int mode) {
  ImSpinner::SpinnerBounceDots(label, radius, thickness, color, speed, dots, mode);
}
#endif

/* C++ definition [2]
   void Spinner::SpinnerZipDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 5)
*/
#ifdef SPINNER_ZIPDOTS
CIMSPINNER_API void SpinnerZipDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerZipDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerZipDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots) {
  ImSpinner::SpinnerZipDots(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [3]
   void Spinner::SpinnerDotsToPoints(const char *label, float radius, float thickness, float offset_k, const ImColor &color = white, float speed = 1.8f, size_t dots = 5)
*/
#ifdef SPINNER_DOTSTOPOINTS
CIMSPINNER_API void SpinnerDotsToPoints(const char *label, float radius, float thickness, float offset_k) {
  ImSpinner::SpinnerDotsToPoints(label, radius, thickness, offset_k);
}
CIMSPINNER_API void SpinnerDotsToPointsEx(const char *label, float radius, float thickness, float offset_k,const ImColor color, float speed, size_t dots) {
  ImSpinner::SpinnerDotsToPoints(label, radius, thickness, offset_k, color, speed, dots);
}
#endif

/* C++ definition [4]
   void Spinner::SpinnerDotsToBar(const char *label, float radius, float thickness, float offset_k, const ImColor &color = white, float speed = 2.8f, size_t dots = 5)
*/
#ifdef SPINNER_DOTSTOBAR
CIMSPINNER_API void SpinnerDotsToBar(const char *label, float radius, float thickness, float offset_k) {
  ImSpinner::SpinnerDotsToBar(label, radius, thickness, offset_k);
}
CIMSPINNER_API void SpinnerDotsToBarEx(const char *label, float radius, float thickness, float offset_k,const ImColor color, float speed, size_t dots) {
  ImSpinner::SpinnerDotsToBar(label, radius, thickness, offset_k, color, speed, dots);
}
#endif

/* C++ definition [5]
   void Spinner::SpinnerWaveDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
*/
#ifdef SPINNER_WAVEDOTS
CIMSPINNER_API void SpinnerWaveDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerWaveDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerWaveDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt) {
  ImSpinner::SpinnerWaveDots(label, radius, thickness, color, speed, lt);
}
#endif

/* C++ definition [6]
   void Spinner::SpinnerFadeDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8, int mode = 0)
*/
#ifdef SPINNER_FADEDOTS
CIMSPINNER_API void SpinnerFadeDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerFadeDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerFadeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, int mode) {
  ImSpinner::SpinnerFadeDots(label, radius, thickness, color, speed, lt, mode);
}
#endif

/* C++ definition [7]
   void Spinner::SpinnerThreeDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
*/
#ifdef SPINNER_THREEDOTS
CIMSPINNER_API void SpinnerThreeDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerThreeDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerThreeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt) {
  ImSpinner::SpinnerThreeDots(label, radius, thickness, color, speed, lt);
}
#endif

/* C++ definition [8]
   void Spinner::SpinnerFiveDots(const char *label, float radius, float thickness, const ImColor &color = 0xffffffff, float speed = 2.8f, int lt = 8)
*/
#ifdef SPINNER_FIVEDOTS
CIMSPINNER_API void SpinnerFiveDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerFiveDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerFiveDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt) {
  ImSpinner::SpinnerFiveDots(label, radius, thickness, color, speed, lt);
}
#endif

/* C++ definition [9]
   void Spinner::SpinnerMultiFadeDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
*/
#ifdef SPINNER_MULTIFADEDOTS
CIMSPINNER_API void SpinnerMultiFadeDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerMultiFadeDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerMultiFadeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt) {
  ImSpinner::SpinnerMultiFadeDots(label, radius, thickness, color, speed, lt);
}
#endif

/* C++ definition [10]
   void Spinner::SpinnerScaleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
*/
#ifdef SPINNER_SCALEDOTS
CIMSPINNER_API void SpinnerScaleDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerScaleDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt) {
  ImSpinner::SpinnerScaleDots(label, radius, thickness, color, speed, lt);
}
#endif

/* C++ definition [11]
   void Spinner::SpinnerMovingDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 3)
*/
#ifdef SPINNER_MOVINGDOTS
CIMSPINNER_API void SpinnerMovingDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerMovingDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerMovingDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots) {
  ImSpinner::SpinnerMovingDots(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [12]
   void Spinner::SpinnerRotateDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int dots = 2, int mode = 0)
*/
#ifdef SPINNER_ROTATEDOTS
CIMSPINNER_API void SpinnerRotateDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerRotateDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerRotateDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots, int mode) {
  ImSpinner::SpinnerRotateDots(label, radius, thickness, color, speed, dots, mode);
}
#endif

/* C++ definition [13]
   void Spinner::SpinnerOrionDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int arcs = 4)
*/
#ifdef SPINNER_ORIONDOTS
CIMSPINNER_API void SpinnerOrionDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerOrionDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerOrionDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int arcs) {
  ImSpinner::SpinnerOrionDots(label, radius, thickness, color, speed, arcs);
}
#endif

/* C++ definition [14]
   void Spinner::SpinnerGalaxyDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int arcs = 4)
*/
#ifdef SPINNER_GALAXYDOTS
CIMSPINNER_API void SpinnerGalaxyDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerGalaxyDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerGalaxyDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int arcs) {
  ImSpinner::SpinnerGalaxyDots(label, radius, thickness, color, speed, arcs);
}
#endif

/* C++ definition [15]
   void Spinner::SpinnerIncDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 6)
*/
#ifdef SPINNER_INCDOTS
CIMSPINNER_API void SpinnerIncDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerIncDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerIncDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots) {
  ImSpinner::SpinnerIncDots(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [16]
   void Spinner::SpinnerIncFullDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 4)
*/
#ifdef SPINNER_INCFULLDOTS
CIMSPINNER_API void SpinnerIncFullDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerIncFullDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerIncFullDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots) {
  ImSpinner::SpinnerIncFullDots(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [17]
   void Spinner::SpinnerIncScaleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 6, float angle = 0.f, int mode = 0)
*/
#ifdef SPINNER_INCSCALEDOTS
CIMSPINNER_API void SpinnerIncScaleDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerIncScaleDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerIncScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, float angle, int mode) {
  ImSpinner::SpinnerIncScaleDots(label, radius, thickness, color, speed, dots, angle, mode);
}
#endif

/* C++ definition [18]
   void Spinner::SpinnerSomeScaleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 6, int mode = 0)
*/
#ifdef SPINNER_SOMESCALEDOTS
CIMSPINNER_API void SpinnerSomeScaleDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSomeScaleDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSomeScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, int mode) {
  ImSpinner::SpinnerSomeScaleDots(label, radius, thickness, color, speed, dots, mode);
}
#endif

/* C++ definition [19]
   void Spinner::SpinnerDotsLoading(const char *label, float radius, float thickness, const ImColor &color, const ImColor &bg, float speed)
*/
#ifdef SPINNER_DOTSLOADING
CIMSPINNER_API void SpinnerDotsLoading(const char *label, float radius, float thickness, const ImColor color, const ImColor bg, float speed) {
  ImSpinner::SpinnerDotsLoading(label, radius, thickness, color, bg, speed);
}
#endif

/* C++ definition [20]
   void Spinner::SpinnerSquareRandomDots(const char *label, float radius, float thickness, const ImColor &bg, const ImColor &color, float speed)
*/
#ifdef SPINNER_SQUARERANDOMDOTS
CIMSPINNER_API void SpinnerSquareRandomDots(const char *label, float radius, float thickness, const ImColor bg, const ImColor color, float speed) {
  ImSpinner::SpinnerSquareRandomDots(label, radius, thickness, bg, color, speed);
}
#endif

/* C++ definition [21]
   void Spinner::SpinnerHboDots(const char *label, float radius, float thickness, const ImColor &color = white, float minfade = 0.0f, float ryk = 0.f, float speed = 1.1f, size_t dots = 6, int mode = 0)
*/
#ifdef SPINNER_HBODOTS
CIMSPINNER_API void SpinnerHboDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerHboDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerHboDotsEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, size_t dots, int mode) {
  ImSpinner::SpinnerHboDots(label, radius, thickness, color, minfade, ryk, speed, dots, mode);
}
#endif

/* C++ definition [22]
   void Spinner::SpinnerMoonDots(const char *label, float radius, float thickness, const ImColor &first, const ImColor &second, float speed = 1.1f)
*/
#ifdef SPINNER_MOONDOTS
CIMSPINNER_API void SpinnerMoonDots(const char *label, float radius, float thickness, const ImColor first, const ImColor second) {
  ImSpinner::SpinnerMoonDots(label, radius, thickness, first, second);
}
CIMSPINNER_API void SpinnerMoonDotsEx(const char *label, float radius, float thickness, const ImColor first, const ImColor second,float speed) {
  ImSpinner::SpinnerMoonDots(label, radius, thickness, first, second, speed);
}
#endif

/* C++ definition [23]
   void Spinner::SpinnerTwinHboDots(const char *label, float radius, float thickness, const ImColor &color = white, float minfade = 0.0f, float ryk = 0.f, float speed = 1.1f, size_t dots = 6, float delta = 0.f)
*/
#ifdef SPINNER_TWINHBODOTS
CIMSPINNER_API void SpinnerTwinHboDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerTwinHboDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerTwinHboDotsEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, size_t dots, float delta) {
  ImSpinner::SpinnerTwinHboDots(label, radius, thickness, color, minfade, ryk, speed, dots, delta);
}
#endif

/* C++ definition [24]
   void Spinner::SpinnerThreeDotsStar(const char *label, float radius, float thickness, const ImColor &color = white, float minfade = 0.0f, float ryk = 0.f, float speed = 1.1f, float delta = 0.f)
*/
#ifdef SPINNER_THREEDOTSSTAR
CIMSPINNER_API void SpinnerThreeDotsStar(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerThreeDotsStar(label, radius, thickness);
}
CIMSPINNER_API void SpinnerThreeDotsStarEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, float delta) {
  ImSpinner::SpinnerThreeDotsStar(label, radius, thickness, color, minfade, ryk, speed, delta);
}
#endif

/* C++ definition [25]
   void Spinner::SpinnerSwingDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
*/
#ifdef SPINNER_SWINGDOTS
CIMSPINNER_API void SpinnerSwingDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerSwingDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerSwingDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerSwingDots(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [26]
   void Spinner::SpinnerDnaDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8, float delta = 0.5f, bool mode = 0)
*/
#ifdef SPINNER_DNADOTS
CIMSPINNER_API void SpinnerDnaDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDnaDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDnaDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, float delta, bool mode) {
  ImSpinner::SpinnerDnaDots(label, radius, thickness, color, speed, lt, delta, mode);
}
#endif

/* C++ definition [27]
   void Spinner::Spinner3SmuggleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 4.8f, int lt = 8, float delta = 0.5f, bool mode = 0)
*/
#ifdef SPINNER_3SMUGGLEDOTS
CIMSPINNER_API void Spinner3SmuggleDots(const char *label, float radius, float thickness) {
  ImSpinner::Spinner3SmuggleDots(label, radius, thickness);
}
CIMSPINNER_API void Spinner3SmuggleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, float delta, bool mode) {
  ImSpinner::Spinner3SmuggleDots(label, radius, thickness, color, speed, lt, delta, mode);
}
#endif

/* C++ definition [28]
   void Spinner::SpinnerDotsTyping(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int dots = 3)
*/
#ifdef SPINNER_DOTSTYPING
CIMSPINNER_API void SpinnerDotsTyping(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsTyping(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsTypingEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots) {
  ImSpinner::SpinnerDotsTyping(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [29]
   void Spinner::SpinnerDotsStep(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int dots = 3)
*/
#ifdef SPINNER_DOTSSTEP
CIMSPINNER_API void SpinnerDotsStep(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsStep(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsStepEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots) {
  ImSpinner::SpinnerDotsStep(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [30]
   void Spinner::SpinnerDotsGather(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.5f, int dots = 3)
*/
#ifdef SPINNER_DOTSGATHER
CIMSPINNER_API void SpinnerDotsGather(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsGather(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsGatherEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots) {
  ImSpinner::SpinnerDotsGather(label, radius, thickness, color, speed, dots);
}
#endif

/* C++ definition [31]
   void Spinner::SpinnerDotsShift(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.5f)
*/
#ifdef SPINNER_DOTSSHIFT
CIMSPINNER_API void SpinnerDotsShift(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsShift(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsShiftEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsShift(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [32]
   void Spinner::SpinnerDotsOrbit(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.66f)
*/
#ifdef SPINNER_DOTSORBIT
CIMSPINNER_API void SpinnerDotsOrbit(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsOrbit(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsOrbitEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsOrbit(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [33]
   void Spinner::SpinnerDotsCircle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.66f)
*/
#ifdef SPINNER_DOTSCIRCLE
CIMSPINNER_API void SpinnerDotsCircle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsCircle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsCircleEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsCircle(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [34]
   void Spinner::SpinnerDotsSquare(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSQUARE
CIMSPINNER_API void SpinnerDotsSquare(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSquare(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSquare(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [35]
   void Spinner::SpinnerDotsShuffle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSHUFFLE
CIMSPINNER_API void SpinnerDotsShuffle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsShuffle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsShuffleEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsShuffle(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [36]
   void Spinner::SpinnerDotsSplit(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSPLIT
CIMSPINNER_API void SpinnerDotsSplit(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSplit(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSplitEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSplit(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [37]
   void Spinner::SpinnerDotsLeader(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSLEADER
CIMSPINNER_API void SpinnerDotsLeader(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsLeader(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsLeaderEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsLeader(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [38]
   void Spinner::SpinnerDotsRolling(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSROLLING
CIMSPINNER_API void SpinnerDotsRolling(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsRolling(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsRollingEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsRolling(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [39]
   void Spinner::SpinnerDotsTriangle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSTRIANGLE
CIMSPINNER_API void SpinnerDotsTriangle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsTriangle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsTriangleEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsTriangle(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [40]
   void Spinner::SpinnerDotsCascade(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSCASCADE
CIMSPINNER_API void SpinnerDotsCascade(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsCascade(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsCascadeEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsCascade(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [41]
   void Spinner::SpinnerDotsSwap(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSWAP
CIMSPINNER_API void SpinnerDotsSwap(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSwap(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSwapEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSwap(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [42]
   void Spinner::SpinnerDotsSpread(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSPREAD
CIMSPINNER_API void SpinnerDotsSpread(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSpread(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSpreadEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSpread(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [43]
   void Spinner::SpinnerDotsTwin(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.5f)
*/
#ifdef SPINNER_DOTSTWIN
CIMSPINNER_API void SpinnerDotsTwin(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsTwin(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsTwinEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsTwin(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [44]
   void Spinner::SpinnerDotsHop(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f / 1.5f)
*/
#ifdef SPINNER_DOTSHOP
CIMSPINNER_API void SpinnerDotsHop(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsHop(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsHopEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsHop(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [45]
   void Spinner::SpinnerDotsJiggle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSJIGGLE
CIMSPINNER_API void SpinnerDotsJiggle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsJiggle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsJiggleEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsJiggle(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [46]
   void Spinner::SpinnerDotsVibrate(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSVIBRATE
CIMSPINNER_API void SpinnerDotsVibrate(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsVibrate(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsVibrateEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsVibrate(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [47]
   void Spinner::SpinnerDotsWiper(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.f)
*/
#ifdef SPINNER_DOTSWIPER
CIMSPINNER_API void SpinnerDotsWiper(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsWiper(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsWiperEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsWiper(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [48]
   void Spinner::SpinnerDotsCollapse(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.5f)
*/
#ifdef SPINNER_DOTSCOLLAPSE
CIMSPINNER_API void SpinnerDotsCollapse(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsCollapse(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsCollapseEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsCollapse(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [49]
   void Spinner::SpinnerDotsFlip(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSFLIP
CIMSPINNER_API void SpinnerDotsFlip(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsFlip(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsFlipEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsFlip(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [50]
   void Spinner::SpinnerDotsTurn(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSTURN
CIMSPINNER_API void SpinnerDotsTurn(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsTurn(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsTurnEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsTurn(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [51]
   void Spinner::SpinnerDotsCarousel(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSCAROUSEL
CIMSPINNER_API void SpinnerDotsCarousel(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsCarousel(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsCarouselEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsCarousel(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [52]
   void Spinner::SpinnerDotsHalfTurn(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSHALFTURN
CIMSPINNER_API void SpinnerDotsHalfTurn(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsHalfTurn(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsHalfTurnEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsHalfTurn(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [53]
   void Spinner::SpinnerDotsSlideFlip(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSLIDEFLIP
CIMSPINNER_API void SpinnerDotsSlideFlip(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSlideFlip(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSlideFlipEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSlideFlip(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [54]
   void Spinner::SpinnerDotsStaggerTurn(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSTAGGERTURN
CIMSPINNER_API void SpinnerDotsStaggerTurn(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsStaggerTurn(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsStaggerTurnEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsStaggerTurn(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [55]
   void Spinner::SpinnerDotsStretch(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSTRETCH
CIMSPINNER_API void SpinnerDotsStretch(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsStretch(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsStretchEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsStretch(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [56]
   void Spinner::SpinnerDotsMirrorStretch(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSMIRRORSTRETCH
CIMSPINNER_API void SpinnerDotsMirrorStretch(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsMirrorStretch(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsMirrorStretchEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsMirrorStretch(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [57]
   void Spinner::SpinnerDotsPinch(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSPINCH
CIMSPINNER_API void SpinnerDotsPinch(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsPinch(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsPinchEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsPinch(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [58]
   void Spinner::SpinnerDotsCorners(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.f)
*/
#ifdef SPINNER_DOTSCORNERS
CIMSPINNER_API void SpinnerDotsCorners(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsCorners(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsCornersEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsCorners(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [59]
   void Spinner::SpinnerDotsNudgeRotate(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSNUDGEROTATE
CIMSPINNER_API void SpinnerDotsNudgeRotate(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsNudgeRotate(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsNudgeRotateEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsNudgeRotate(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [60]
   void Spinner::SpinnerDotsUnfold(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSUNFOLD
CIMSPINNER_API void SpinnerDotsUnfold(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsUnfold(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsUnfoldEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsUnfold(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [61]
   void Spinner::SpinnerDotsShuttle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSHUTTLE
CIMSPINNER_API void SpinnerDotsShuttle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsShuttle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsShuttleEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsShuttle(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [62]
   void Spinner::SpinnerDotsSpreadShuttle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSPREADSHUTTLE
CIMSPINNER_API void SpinnerDotsSpreadShuttle(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSpreadShuttle(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSpreadShuttleEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSpreadShuttle(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [63]
   void Spinner::SpinnerDotsTriad(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSTRIAD
CIMSPINNER_API void SpinnerDotsTriad(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsTriad(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsTriadEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsTriad(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [64]
   void Spinner::SpinnerDotsSatellite(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f)
*/
#ifdef SPINNER_DOTSSATELLITE
CIMSPINNER_API void SpinnerDotsSatellite(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsSatellite(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsSatelliteEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsSatellite(label, radius, thickness, color, speed);
}
#endif

/* C++ definition [65]
   void Spinner::SpinnerDotsTrack(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 0.5f)
*/
#ifdef SPINNER_DOTSTRACK
CIMSPINNER_API void SpinnerDotsTrack(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerDotsTrack(label, radius, thickness);
}
CIMSPINNER_API void SpinnerDotsTrackEx(const char *label, float radius, float thickness,const ImColor color, float speed) {
  ImSpinner::SpinnerDotsTrack(label, radius, thickness, color, speed);
}
#endif
