/*
 * Auto-generated-style C wrapper for ../imspinner_dots.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "cimspinner_config.h"
//#define SPINNER_BOUNCEDOTS
//#define SPINNER_ZIPDOTS
//#define SPINNER_DOTSTOPOINTS
//#define SPINNER_DOTSTOBAR
//#define SPINNER_WAVEDOTS
//#define SPINNER_FADEDOTS
//#define SPINNER_THREEDOTS
//#define SPINNER_FIVEDOTS
//#define SPINNER_MULTIFADEDOTS
//#define SPINNER_SCALEDOTS
//#define SPINNER_MOVINGDOTS
//#define SPINNER_ROTATEDOTS
//#define SPINNER_ORIONDOTS
//#define SPINNER_GALAXYDOTS
//#define SPINNER_INCDOTS
//#define SPINNER_INCFULLDOTS
//#define SPINNER_INCSCALEDOTS
//#define SPINNER_SOMESCALEDOTS
//#define SPINNER_DOTSLOADING
//#define SPINNER_SQUARERANDOMDOTS
//#define SPINNER_HBODOTS
//#define SPINNER_MOONDOTS
//#define SPINNER_TWINHBODOTS
//#define SPINNER_THREEDOTSSTAR
//#define SPINNER_SWINGDOTS
//#define SPINNER_DNADOTS
//#define SPINNER_3SMUGGLEDOTS
//#define SPINNER_DOTSTYPING
//#define SPINNER_DOTSSTEP
//#define SPINNER_DOTSGATHER
//#define SPINNER_DOTSSHIFT
//#define SPINNER_DOTSORBIT
//#define SPINNER_DOTSCIRCLE
//#define SPINNER_DOTSSQUARE
//#define SPINNER_DOTSSHUFFLE
//#define SPINNER_DOTSSPLIT
//#define SPINNER_DOTSLEADER
//#define SPINNER_DOTSROLLING
//#define SPINNER_DOTSTRIANGLE
//#define SPINNER_DOTSCASCADE
//#define SPINNER_DOTSSWAP
//#define SPINNER_DOTSSPREAD
//#define SPINNER_DOTSTWIN
//#define SPINNER_DOTSHOP
//#define SPINNER_DOTSJIGGLE
//#define SPINNER_DOTSVIBRATE
//#define SPINNER_DOTSWIPER
//#define SPINNER_DOTSCOLLAPSE
//#define SPINNER_DOTSFLIP
//#define SPINNER_DOTSTURN
//#define SPINNER_DOTSCAROUSEL
//#define SPINNER_DOTSHALFTURN
//#define SPINNER_DOTSSLIDEFLIP
//#define SPINNER_DOTSSTAGGERTURN
//#define SPINNER_DOTSSTRETCH
//#define SPINNER_DOTSMIRRORSTRETCH
//#define SPINNER_DOTSPINCH
//#define SPINNER_DOTSCORNERS
//#define SPINNER_DOTSNUDGEROTATE
//#define SPINNER_DOTSUNFOLD
//#define SPINNER_DOTSSHUTTLE
//#define SPINNER_DOTSSPREADSHUTTLE
//#define SPINNER_DOTSTRIAD
//#define SPINNER_DOTSSATELLITE
//#define SPINNER_DOTSTRACK

#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#ifndef CIMSPINNER_API
  #define CIMSPINNER_API
#endif

CIMSPINNER_API void SpinnerBounceDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerBounceDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, int mode);
CIMSPINNER_API void SpinnerZipDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerZipDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerDotsToPoints(const char *label, float radius, float thickness, float offset_k);
CIMSPINNER_API void SpinnerDotsToPointsEx(const char *label, float radius, float thickness, float offset_k,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerDotsToBar(const char *label, float radius, float thickness, float offset_k);
CIMSPINNER_API void SpinnerDotsToBarEx(const char *label, float radius, float thickness, float offset_k,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerWaveDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerWaveDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerFadeDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFadeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, int mode);
CIMSPINNER_API void SpinnerThreeDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerThreeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerFiveDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFiveDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerMultiFadeDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMultiFadeDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerScaleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt);
CIMSPINNER_API void SpinnerMovingDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMovingDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerRotateDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerRotateDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots, int mode);
CIMSPINNER_API void SpinnerOrionDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerOrionDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int arcs);
CIMSPINNER_API void SpinnerGalaxyDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerGalaxyDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int arcs);
CIMSPINNER_API void SpinnerIncDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerIncDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerIncFullDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerIncFullDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots);
CIMSPINNER_API void SpinnerIncScaleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerIncScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, float angle, int mode);
CIMSPINNER_API void SpinnerSomeScaleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSomeScaleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, size_t dots, int mode);
CIMSPINNER_API void SpinnerDotsLoading(const char *label, float radius, float thickness, const ImColor color, const ImColor bg, float speed);
CIMSPINNER_API void SpinnerSquareRandomDots(const char *label, float radius, float thickness, const ImColor bg, const ImColor color, float speed);
CIMSPINNER_API void SpinnerHboDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerHboDotsEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, size_t dots, int mode);
CIMSPINNER_API void SpinnerMoonDots(const char *label, float radius, float thickness, const ImColor first, const ImColor second);
CIMSPINNER_API void SpinnerMoonDotsEx(const char *label, float radius, float thickness, const ImColor first, const ImColor second,float speed);
CIMSPINNER_API void SpinnerTwinHboDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTwinHboDotsEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, size_t dots, float delta);
CIMSPINNER_API void SpinnerThreeDotsStar(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerThreeDotsStarEx(const char *label, float radius, float thickness,const ImColor color, float minfade, float ryk, float speed, float delta);
CIMSPINNER_API void SpinnerSwingDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSwingDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDnaDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDnaDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, float delta, bool mode);
CIMSPINNER_API void Spinner3SmuggleDots(const char *label, float radius, float thickness);
CIMSPINNER_API void Spinner3SmuggleDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int lt, float delta, bool mode);
CIMSPINNER_API void SpinnerDotsTyping(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsTypingEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots);
CIMSPINNER_API void SpinnerDotsStep(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsStepEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots);
CIMSPINNER_API void SpinnerDotsGather(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsGatherEx(const char *label, float radius, float thickness,const ImColor color, float speed, int dots);
CIMSPINNER_API void SpinnerDotsShift(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsShiftEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsOrbit(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsOrbitEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsCircle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsCircleEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSquare(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsShuffle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsShuffleEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSplit(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSplitEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsLeader(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsLeaderEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsRolling(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsRollingEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsTriangle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsTriangleEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsCascade(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsCascadeEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSwap(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSwapEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSpread(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSpreadEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsTwin(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsTwinEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsHop(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsHopEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsJiggle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsJiggleEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsVibrate(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsVibrateEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsWiper(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsWiperEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsCollapse(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsCollapseEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsFlip(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsFlipEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsTurn(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsTurnEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsCarousel(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsCarouselEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsHalfTurn(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsHalfTurnEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSlideFlip(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSlideFlipEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsStaggerTurn(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsStaggerTurnEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsStretch(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsStretchEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsMirrorStretch(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsMirrorStretchEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsPinch(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsPinchEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsCorners(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsCornersEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsNudgeRotate(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsNudgeRotateEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsUnfold(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsUnfoldEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsShuttle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsShuttleEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSpreadShuttle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSpreadShuttleEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsTriad(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsTriadEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsSatellite(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsSatelliteEx(const char *label, float radius, float thickness,const ImColor color, float speed);
CIMSPINNER_API void SpinnerDotsTrack(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDotsTrackEx(const char *label, float radius, float thickness,const ImColor color, float speed);
#ifdef __cplusplus
}
#endif
