/*
 * Auto-generated-style C wrapper for ../imspinner_shapes.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "cimspinner_config.h"
//#define SPINNER_MORPHSHAPE
//#define SPINNER_FLIPTRIANGLE
//#define SPINNER_FOLDSQUARE
//#define SPINNER_PINWHEEL
//#define SPINNER_CORNERSQUARES
//#define SPINNER_SPLITSQUARE
//#define SPINNER_CORNERBURST
//#define SPINNER_SKEWSQUARE
//#define SPINNER_TUMBLESQUARE
//#define SPINNER_TRIDIAMOND
//#define SPINNER_TWINBLADES
//#define SPINNER_CROSSBLADES
//#define SPINNER_DRIFTSQUARE
//#define SPINNER_PIEBOUNCE
//#define SPINNER_LEAPFROG
//#define SPINNER_PLUSSQUARES
//#define SPINNER_SEVENMARCH
//#define SPINNER_CORNERARCS
//#define SPINNER_WALKBLOCKS
//#define SPINNER_TUMBLEHALFDISC
//#define SPINNER_FOLDHALFDISC
//#define SPINNER_WIPERARROW
//#define SPINNER_SKEWSQUARES
//#define SPINNER_STRETCHSQUARES
//#define SPINNER_TRIPIE
//#define SPINNER_SHUFFLEBARS
//#define SPINNER_HINGETUMBLE
//#define SPINNER_DIAGONALFLIP
//#define SPINNER_PULSEGRID
//#define SPINNER_MARCHGRID
//#define SPINNER_SPINBARS
//#define SPINNER_MORPHDOTS
//#define SPINNER_COMBDISCS
//#define SPINNER_ORBITDISC

#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#ifndef CIMSPINNER_API
  #define CIMSPINNER_API
#endif

CIMSPINNER_API void SpinnerMorphShape(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMorphShapeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerFlipTriangle(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFlipTriangleEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerFoldSquare(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFoldSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerPinwheel(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPinwheelEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerCornerSquares(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCornerSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerSplitSquare(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSplitSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerCornerBurst(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCornerBurstEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerSkewSquare(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSkewSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerTumbleSquare(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTumbleSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerTriDiamond(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTriDiamondEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerTwinBlades(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTwinBladesEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerCrossBlades(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCrossBladesEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerDriftSquare(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDriftSquareEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerPieBounce(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPieBounceEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerLeapFrog(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerLeapFrogEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerPlusSquares(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPlusSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerSevenMarch(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSevenMarchEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerCornerArcs(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCornerArcsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerWalkBlocks(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerWalkBlocksEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerTumbleHalfDisc(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTumbleHalfDiscEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerFoldHalfDisc(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerFoldHalfDiscEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerWiperArrow(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerWiperArrowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerSkewSquares(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSkewSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerStretchSquares(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerStretchSquaresEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerTriPie(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerTriPieEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerShuffleBars(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerShuffleBarsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerHingeTumble(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerHingeTumbleEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerDiagonalFlip(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerDiagonalFlipEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerPulseGrid(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerPulseGridEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerMarchGrid(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMarchGridEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerSpinBars(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerSpinBarsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerMorphDots(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerMorphDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerCombDiscs(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerCombDiscsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
CIMSPINNER_API void SpinnerOrbitDisc(const char *label, float radius, float thickness);
CIMSPINNER_API void SpinnerOrbitDiscEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode);
#ifdef __cplusplus
}
#endif
