#pragma once

#define SPINNER_RAINBOWMIX
#define SPINNER_DNADOTS
#define SPINNER_ANG8
#define SPINNER_CLOCK
#define SPINNER_PULSAR
#define SPINNER_ATOM



#define SPINNER_FADEBARS
#define SPINNER_BARSROTATEFADE
#define SPINNER_BARSSCALEMIDDLE
#define SPINNER_BARCHARTSINE
#define SPINNER_BARCHARTADVSINE
#define SPINNER_DOTSTOBAR
#define SPINNER_BARCHARTRAINBOW


#define SPINNER_SWINGDOTS

#define SPINNER_TEXTFADE
#define SPINNER_TEXTFADING
#define SPINNER_TEXTUNDERLINE
#define SPINNER_TEXTUNDERLINEDOTS
#define SPINNER_TEXTTYPING
#define SPINNER_TEXTSCROLL

#define SPINNER_MORPHSHAPE
#define SPINNER_FLIPTRIANGLE
#define SPINNER_FOLDSQUARE
#define SPINNER_PINWHEEL
#define SPINNER_CORNERSQUARES
#define SPINNER_SPLITSQUARE

#define SPINNER_MORPHSHAPE
#define SPINNER_FLIPTRIANGLE
#define SPINNER_FOLDSQUARE
#define SPINNER_PINWHEEL
#define SPINNER_CORNERSQUARES
#define SPINNER_SPLITSQUARE
