/*
 * Auto-generated-style C wrapper for ../imspinner_bars.h following the ImSpinner project's
 * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
 *
 * This file has been auto generated by srcript, see genCimSpinner.rb
*/

#include "imspinner_bars.h"
#include "cimspinner_bars.h"


/* C++ definition [1]
   void Spinner::SpinnerFadeBars(const char *label, float w, const ImColor &color = white, float speed = 2.8f, size_t bars = 3, bool scale = false)
*/
#ifdef SPINNER_FADEBARS
CIMSPINNER_API void SpinnerFadeBars(const char *label, float w) {
  ImSpinner::SpinnerFadeBars(label, w);
}
CIMSPINNER_API void SpinnerFadeBarsEx(const char *label, float w,const ImColor color, float speed, size_t bars, bool scale) {
  ImSpinner::SpinnerFadeBars(label, w, color, speed, bars, scale);
}
#endif

/* C++ definition [2]
   void Spinner::SpinnerBarsRotateFade(const char *label, float rmin, float rmax , float thickness, const ImColor &color = white, float speed = 2.8f, size_t bars = 6)
*/
#ifdef SPINNER_BARSROTATEFADE
CIMSPINNER_API void SpinnerBarsRotateFade(const char *label, float rmin, float rmax , float thickness) {
  ImSpinner::SpinnerBarsRotateFade(label, rmin, rmax, thickness);
}
CIMSPINNER_API void SpinnerBarsRotateFadeEx(const char *label, float rmin, float rmax , float thickness,const ImColor color, float speed, size_t bars) {
  ImSpinner::SpinnerBarsRotateFade(label, rmin, rmax, thickness, color, speed, bars);
}
#endif

/* C++ definition [3]
   void Spinner::SpinnerBarsScaleMiddle(const char *label, float w, const ImColor &color = white, float speed = 2.8f, size_t bars = 3)
*/
#ifdef SPINNER_BARSSCALEMIDDLE
CIMSPINNER_API void SpinnerBarsScaleMiddle(const char *label, float w) {
  ImSpinner::SpinnerBarsScaleMiddle(label, w);
}
CIMSPINNER_API void SpinnerBarsScaleMiddleEx(const char *label, float w,const ImColor color, float speed, size_t bars) {
  ImSpinner::SpinnerBarsScaleMiddle(label, w, color, speed, bars);
}
#endif

/* C++ definition [4]
   void Spinner::SpinnerBarChartSine(const char *label, float radius, float thickness, const ImColor &color, float speed, int bars = 5, int mode = 0)
*/
#ifdef SPINNER_BARCHARTSINE
CIMSPINNER_API void SpinnerBarChartSine(const char *label, float radius, float thickness, const ImColor color, float speed) {
  ImSpinner::SpinnerBarChartSine(label, radius, thickness, color, speed);
}
CIMSPINNER_API void SpinnerBarChartSineEx(const char *label, float radius, float thickness, const ImColor color, float speed,int bars, int mode) {
  ImSpinner::SpinnerBarChartSine(label, radius, thickness, color, speed, bars, mode);
}
#endif

/* C++ definition [5]
   void Spinner::SpinnerBarChartAdvSine(const char *label, float radius, float thickness, const ImColor &color, float speed, int mode = 0)
*/
#ifdef SPINNER_BARCHARTADVSINE
CIMSPINNER_API void SpinnerBarChartAdvSine(const char *label, float radius, float thickness, const ImColor color, float speed) {
  ImSpinner::SpinnerBarChartAdvSine(label, radius, thickness, color, speed);
}
CIMSPINNER_API void SpinnerBarChartAdvSineEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode) {
  ImSpinner::SpinnerBarChartAdvSine(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [6]
   void Spinner::SpinnerBarChartAdvSineFade(const char *label, float radius, float thickness, const ImColor &color, float speed, int mode = 0)
*/
#ifdef SPINNER_BARCHARTADVSINEFADE
CIMSPINNER_API void SpinnerBarChartAdvSineFade(const char *label, float radius, float thickness, const ImColor color, float speed) {
  ImSpinner::SpinnerBarChartAdvSineFade(label, radius, thickness, color, speed);
}
CIMSPINNER_API void SpinnerBarChartAdvSineFadeEx(const char *label, float radius, float thickness, const ImColor color, float speed,int mode) {
  ImSpinner::SpinnerBarChartAdvSineFade(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [7]
   void Spinner::SpinnerBarChartRainbow(const char *label, float radius, float thickness, const ImColor &color, float speed, int bars = 5, int mode = 0)
*/
#ifdef SPINNER_BARCHARTRAINBOW
CIMSPINNER_API void SpinnerBarChartRainbow(const char *label, float radius, float thickness, const ImColor color, float speed) {
  ImSpinner::SpinnerBarChartRainbow(label, radius, thickness, color, speed);
}
CIMSPINNER_API void SpinnerBarChartRainbowEx(const char *label, float radius, float thickness, const ImColor color, float speed,int bars, int mode) {
  ImSpinner::SpinnerBarChartRainbow(label, radius, thickness, color, speed, bars, mode);
}
#endif

/* C++ definition [8]
   void Spinner::SpinnerFluid(const char *label, float radius, const ImColor &color, float speed, int bars = 3)
*/
#ifdef SPINNER_FLUID
CIMSPINNER_API void SpinnerFluid(const char *label, float radius, const ImColor color, float speed) {
  ImSpinner::SpinnerFluid(label, radius, color, speed);
}
CIMSPINNER_API void SpinnerFluidEx(const char *label, float radius, const ImColor color, float speed,int bars) {
  ImSpinner::SpinnerFluid(label, radius, color, speed, bars);
}
#endif

/* C++ definition [9]
   void Spinner::SpinnerFluidPoints(const char *label, float radius, float thickness, const ImColor &color, float speed, size_t dots = 6, float delta = 0.35f)
*/
#ifdef SPINNER_FLUIDPOINTS
CIMSPINNER_API void SpinnerFluidPoints(const char *label, float radius, float thickness, const ImColor color, float speed) {
  ImSpinner::SpinnerFluidPoints(label, radius, thickness, color, speed);
}
CIMSPINNER_API void SpinnerFluidPointsEx(const char *label, float radius, float thickness, const ImColor color, float speed,size_t dots, float delta) {
  ImSpinner::SpinnerFluidPoints(label, radius, thickness, color, speed, dots, delta);
}
#endif

/* C++ definition [10]
   void Spinner::SpinnerBarsSeqPulse(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSEQPULSE
CIMSPINNER_API void SpinnerBarsSeqPulse(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSeqPulse(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSeqPulseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSeqPulse(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [11]
   void Spinner::SpinnerBarsCascadeGrow(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCASCADEGROW
CIMSPINNER_API void SpinnerBarsCascadeGrow(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsCascadeGrow(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsCascadeGrowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsCascadeGrow(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [12]
   void Spinner::SpinnerBarsRise(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSRISE
CIMSPINNER_API void SpinnerBarsRise(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsRise(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsRiseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsRise(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [13]
   void Spinner::SpinnerBarsCornerHop(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCORNERHOP
CIMSPINNER_API void SpinnerBarsCornerHop(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsCornerHop(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsCornerHopEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsCornerHop(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [14]
   void Spinner::SpinnerBarsDiagonalGrow(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSDIAGONALGROW
CIMSPINNER_API void SpinnerBarsDiagonalGrow(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsDiagonalGrow(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsDiagonalGrowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsDiagonalGrow(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [15]
   void Spinner::SpinnerBarsBounceCenter(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSBOUNCECENTER
CIMSPINNER_API void SpinnerBarsBounceCenter(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsBounceCenter(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsBounceCenterEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsBounceCenter(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [16]
   void Spinner::SpinnerBarsScaleAlt(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSCALEALT
CIMSPINNER_API void SpinnerBarsScaleAlt(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsScaleAlt(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsScaleAltEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsScaleAlt(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [17]
   void Spinner::SpinnerBarsCornerWave(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCORNERWAVE
CIMSPINNER_API void SpinnerBarsCornerWave(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsCornerWave(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsCornerWaveEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsCornerWave(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [18]
   void Spinner::SpinnerBarsJump(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSJUMP
CIMSPINNER_API void SpinnerBarsJump(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsJump(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsJumpEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsJump(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [19]
   void Spinner::SpinnerBarsDoubleRow(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSDOUBLEROW
CIMSPINNER_API void SpinnerBarsDoubleRow(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsDoubleRow(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsDoubleRowEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsDoubleRow(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [20]
   void Spinner::SpinnerBarsSixPulse(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSIXPULSE
CIMSPINNER_API void SpinnerBarsSixPulse(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSixPulse(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSixPulseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSixPulse(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [21]
   void Spinner::SpinnerBarsSixStagger(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSIXSTAGGER
CIMSPINNER_API void SpinnerBarsSixStagger(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSixStagger(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSixStaggerEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSixStagger(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [22]
   void Spinner::SpinnerBarsMorphPlus(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSMORPHPLUS
CIMSPINNER_API void SpinnerBarsMorphPlus(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsMorphPlus(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsMorphPlusEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsMorphPlus(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [23]
   void Spinner::SpinnerBarsFlipSix(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSFLIPSIX
CIMSPINNER_API void SpinnerBarsFlipSix(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsFlipSix(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsFlipSixEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsFlipSix(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [24]
   void Spinner::SpinnerBarsSwapTriBottom(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSWAPTRIBOTTOM
CIMSPINNER_API void SpinnerBarsSwapTriBottom(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSwapTriBottom(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSwapTriBottomEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSwapTriBottom(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [25]
   void Spinner::SpinnerBarsSwapTriZigzag(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSWAPTRIZIGZAG
CIMSPINNER_API void SpinnerBarsSwapTriZigzag(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSwapTriZigzag(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSwapTriZigzagEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSwapTriZigzag(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [26]
   void Spinner::SpinnerBarsMorphDiagonal(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSMORPHDIAGONAL
CIMSPINNER_API void SpinnerBarsMorphDiagonal(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsMorphDiagonal(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsMorphDiagonalEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsMorphDiagonal(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [27]
   void Spinner::SpinnerBarsSlideDiagonal(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSLIDEDIAGONAL
CIMSPINNER_API void SpinnerBarsSlideDiagonal(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSlideDiagonal(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSlideDiagonalEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSlideDiagonal(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [28]
   void Spinner::SpinnerBarsConicAlternate(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCONICALTERNATE
CIMSPINNER_API void SpinnerBarsConicAlternate(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsConicAlternate(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsConicAlternateEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsConicAlternate(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [29]
   void Spinner::SpinnerBarsConicWalk(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCONICWALK
CIMSPINNER_API void SpinnerBarsConicWalk(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsConicWalk(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsConicWalkEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsConicWalk(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [30]
   void Spinner::SpinnerBarsMarchIn(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSMARCHIN
CIMSPINNER_API void SpinnerBarsMarchIn(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsMarchIn(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsMarchInEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsMarchIn(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [31]
   void Spinner::SpinnerBarsMarchDown(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSMARCHDOWN
CIMSPINNER_API void SpinnerBarsMarchDown(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsMarchDown(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsMarchDownEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsMarchDown(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [32]
   void Spinner::SpinnerBarsWaveSkew(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSWAVESKEW
CIMSPINNER_API void SpinnerBarsWaveSkew(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsWaveSkew(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsWaveSkewEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsWaveSkew(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [33]
   void Spinner::SpinnerBarsRowDrop(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSROWDROP
CIMSPINNER_API void SpinnerBarsRowDrop(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsRowDrop(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsRowDropEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsRowDrop(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [34]
   void Spinner::SpinnerBarsZigzagRows(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSZIGZAGROWS
CIMSPINNER_API void SpinnerBarsZigzagRows(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsZigzagRows(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsZigzagRowsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsZigzagRows(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [35]
   void Spinner::SpinnerBarsFillCascade(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSFILLCASCADE
CIMSPINNER_API void SpinnerBarsFillCascade(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsFillCascade(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsFillCascadeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsFillCascade(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [36]
   void Spinner::SpinnerBarsPingPongRows(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSPINGPONGROWS
CIMSPINNER_API void SpinnerBarsPingPongRows(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsPingPongRows(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsPingPongRowsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsPingPongRows(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [37]
   void Spinner::SpinnerBarsWaveRowsWide(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSWAVEROWSWIDE
CIMSPINNER_API void SpinnerBarsWaveRowsWide(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsWaveRowsWide(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsWaveRowsWideEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsWaveRowsWide(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [38]
   void Spinner::SpinnerBarsGridFade(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSGRIDFADE
CIMSPINNER_API void SpinnerBarsGridFade(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsGridFade(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsGridFadeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsGridFade(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [39]
   void Spinner::SpinnerBarsGridSpread(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSGRIDSPREAD
CIMSPINNER_API void SpinnerBarsGridSpread(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsGridSpread(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsGridSpreadEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsGridSpread(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [40]
   void Spinner::SpinnerBarsStretch(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSTRETCH
CIMSPINNER_API void SpinnerBarsStretch(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsStretch(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsStretchEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsStretch(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [41]
   void Spinner::SpinnerBarsStretchSeq(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSTRETCHSEQ
CIMSPINNER_API void SpinnerBarsStretchSeq(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsStretchSeq(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsStretchSeqEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsStretchSeq(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [42]
   void Spinner::SpinnerBarsBounceBall(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSBOUNCEBALL
CIMSPINNER_API void SpinnerBarsBounceBall(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsBounceBall(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsBounceBallEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsBounceBall(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [43]
   void Spinner::SpinnerBarsKnockDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSKNOCKDOTS
CIMSPINNER_API void SpinnerBarsKnockDots(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsKnockDots(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsKnockDotsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsKnockDots(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [44]
   void Spinner::SpinnerBarsStaircase(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSTAIRCASE
CIMSPINNER_API void SpinnerBarsStaircase(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsStaircase(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsStaircaseEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsStaircase(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [45]
   void Spinner::SpinnerBarsKnockAway(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSKNOCKAWAY
CIMSPINNER_API void SpinnerBarsKnockAway(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsKnockAway(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsKnockAwayEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsKnockAway(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [46]
   void Spinner::SpinnerBarsGates(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSGATES
CIMSPINNER_API void SpinnerBarsGates(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsGates(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsGatesEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsGates(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [47]
   void Spinner::SpinnerBarsCapture(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCAPTURE
CIMSPINNER_API void SpinnerBarsCapture(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsCapture(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsCaptureEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsCapture(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [48]
   void Spinner::SpinnerBarsEscape(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSESCAPE
CIMSPINNER_API void SpinnerBarsEscape(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsEscape(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsEscapeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsEscape(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [49]
   void Spinner::SpinnerBarsDevour(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSDEVOUR
CIMSPINNER_API void SpinnerBarsDevour(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsDevour(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsDevourEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsDevour(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [50]
   void Spinner::SpinnerBarsLift(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSLIFT
CIMSPINNER_API void SpinnerBarsLift(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsLift(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsLiftEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsLift(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [51]
   void Spinner::SpinnerBarsGapSlide(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSGAPSLIDE
CIMSPINNER_API void SpinnerBarsGapSlide(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsGapSlide(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsGapSlideEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsGapSlide(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [52]
   void Spinner::SpinnerBarsConverge(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSCONVERGE
CIMSPINNER_API void SpinnerBarsConverge(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsConverge(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsConvergeEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsConverge(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [53]
   void Spinner::SpinnerBarsSwapEnds(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSWAPENDS
CIMSPINNER_API void SpinnerBarsSwapEnds(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSwapEnds(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSwapEndsEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSwapEnds(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [54]
   void Spinner::SpinnerBarsRelay(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSRELAY
CIMSPINNER_API void SpinnerBarsRelay(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsRelay(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsRelayEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsRelay(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [55]
   void Spinner::SpinnerBarsPush(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSPUSH
CIMSPINNER_API void SpinnerBarsPush(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsPush(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsPushEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsPush(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [56]
   void Spinner::SpinnerBarsPushWave(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSPUSHWAVE
CIMSPINNER_API void SpinnerBarsPushWave(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsPushWave(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsPushWaveEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsPushWave(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [57]
   void Spinner::SpinnerBarsGather(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSGATHER
CIMSPINNER_API void SpinnerBarsGather(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsGather(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsGatherEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsGather(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [58]
   void Spinner::SpinnerBarsSplit(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSPLIT
CIMSPINNER_API void SpinnerBarsSplit(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSplit(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSplitEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSplit(label, radius, thickness, color, speed, mode);
}
#endif

/* C++ definition [59]
   void Spinner::SpinnerBarsSlot(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.f, int mode = 0)
*/
#ifdef SPINNER_BARSSLOT
CIMSPINNER_API void SpinnerBarsSlot(const char *label, float radius, float thickness) {
  ImSpinner::SpinnerBarsSlot(label, radius, thickness);
}
CIMSPINNER_API void SpinnerBarsSlotEx(const char *label, float radius, float thickness,const ImColor color, float speed, int mode) {
  ImSpinner::SpinnerBarsSlot(label, radius, thickness, color, speed, mode);
}
#endif
