# The MIT License (MIT)
#
# Copyright (c) 2025 - 2026 dinau
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Generate C++ sources and headers from "imspinner{, _dots, _bars, _shapes, _text}.h" written in C++.
#
#     Input file: ./imspinner_*.h
#     Output files:
#       ./cimspinner.h
#       ./cimspinner.cpp
#       ./cmspinner_*.h
#       ./cmspinner_*.cpp
#     (Config file: ./cimspinner_config.h (written by hand))
#
#     Usage:
#       $ ruby genCimSpinner.rb

def msgLicense(headerName)
  str = <<~EOF
    /*
     * Auto-generated-style C wrapper for #{headerName} following the ImSpinner project's
     * conventions (https://github.com/dalerank/imspinner, MIT License, Copyright (c) 2021-2022 Dalerank).
     *
     * This file has been auto generated by srcript, see genCimSpinner.rb
    */

  EOF
end

require 'fileutils'

FileUtils.mkdir_p('cimspinner')
Groups = ['', 'dots', 'bars', 'shapes', 'text']
$totalFuncs = 0
for group in Groups
  imspinner_group = 'imspinner'
  imspinner_group += '_' + group if group != ''
  outHeader = 'c' + imspinner_group + '.h'
  outCpp    = 'c' + imspinner_group + '.cpp'
  cppHeader = '../' + imspinner_group + '.h'
  funcNumber = 1
  File.open(cppHeader) do |fp|
    puts "Reading .. #{cppHeader}"
    cppFile = []
    cppFile.push "#include \"#{File.basename(cppHeader)}\""
    #cppFile.push '#include "cimspinner_config.h"'
    cppFile.push "#include \"#{File.basename(outHeader)}\""
    cppFile.push ''
    cfuncHeader = []
    cfuncHeader.push "\n#pragma once"
    cfuncHeader.push '#ifdef __cplusplus'
    cfuncHeader.push 'extern "C" {'
    cfuncHeader.push '#endif'
    cfuncHeader.push "\n#ifndef CIMSPINNER_API\n  #define CIMSPINNER_API\n#endif"
    cfuncHeader.push ''
    aryEnableDefine = []
    fp.each do |line|
      next unless line =~ /\s+inline\s+void\s+(Spinner\w+)\((.+)\)/
      cppArgsLong = []
      cppArgsShort = []
      cArgsLongDef = []
      cArgsShortDef = []
      funcname = Regexp.last_match(1)
      cppArgs = Regexp.last_match(2)
      ######
      cfuncHeader.push 'typedef ImColor LeafColor(int);' if line =~ /LeafColor/
      ######
      cppFile.push  "\n/* C++ definition [#{funcNumber}]"
      cppFile.push  "   void Spinner::#{funcname}(#{cppArgs.gsub('/*', '').gsub('*/', '')})"
      cppFile.push  '*/'
      # get short argumants
      # void SpinnerFadeBars(const char *label, float w, const ImColor &color = white, float speed = 2.8f, size_t bars = 3, bool scale = false)
      #  cppArgs -->         const char *label, float w, const ImColor &color = white, float speed = 2.8f, size_t bars = 3, bool scale = false
      cppArgs.split(',').each do |arg|
        if !arg.include? '='
          checkArg = arg.strip.gsub('(', '').gsub(')', '') # Check pattern: "const ImColor &color = ImColor(0xC0, 0x29, 0x42)," => "0x29" and "0x42)"
          if Integer(checkArg, exception: false) or Float(checkArg, exception: false)
            # print "\n", checkArg," :: ", arg
          else
            # C function args short
            cArgsShortDef.push arg.gsub('&', '').gsub('/*', '').gsub('*/', '')
            # Cpp args short
            cppArgsShort.push arg.gsub('/*', '').gsub('*/', '').split(' ').last.gsub('*', '').gsub('&', '')
          end
        else # Long argument
          cArgsLongDef.push arg.split('=')[0].gsub('&', '').strip
          cppArgsLong.push  arg.split('=')[0].split(' ').last.gsub('&', '').gsub('*', '')
        end
      end
      #-----------------------------------------------------------
      # Generate C functions in header: Short arguments functions
      #-----------------------------------------------------------
      sEnableDefine = "SPINNER_#{funcname.split('Spinner')[1].upcase}"
      aryEnableDefine.push "//#define #{sEnableDefine}"
      cargs = cArgsShortDef.join(',')
      cfunc = "CIMSPINNER_API void #{funcname}(#{cargs})"
      cfuncHeader.push cfunc + ";\n"
      #--------------------------------------------------
      # Generate cpp functions that have short arguments
      #--------------------------------------------------
      cppFile.push "#ifdef #{sEnableDefine}"
      cppFile.push "#{cfunc} \{"
      shortArgs = cppArgsShort.join(', ')
      cppFile.push "  ImSpinner::#{funcname}(#{shortArgs});"
      cppFile.push '}'
      #-----------------------------------------------------------
      # Generate C functions in header : Long arguments functions
      #-----------------------------------------------------------
      if 0 != cArgsLongDef.length
        cargs = cargs + ',' + cArgsLongDef.join(', ')
        cfunc = "CIMSPINNER_API void #{funcname}Ex(#{cargs})"
        cfuncHeader.push cfunc + ";\n"
        cppFile.push "#{cfunc} \{"
        # #-------------------------------------------------
        ## Generate cpp functions that have long arguments
        # #-------------------------------------------------
        longArgs = cppArgsLong.join(', ')
        cppFile.push "  ImSpinner::#{funcname}(#{shortArgs}, #{longArgs});"
        cppFile.push '}'
      end
      cppFile.push '#endif'
      funcNumber += 1
    end

    # Output CPP source
    File.open(outCpp, 'w') do |fp|
      fp.puts msgLicense(cppHeader)
      cppFile.each do |line|
        fp.puts line
      end
      puts "Generated: #{outCpp}"
    end

    # Output C Header file
    File.open(outHeader, 'w') do |fp|
      fp.puts msgLicense(cppHeader)
      fp.puts '#include "cimspinner_config.h"'
      aryEnableDefine.each do |line|
        fp.puts line.chomp
      end
      cfuncHeader.each do |line|
        fp.puts line.chomp
      end
      fp.puts '#ifdef __cplusplus'
      fp.puts '}'
      fp.puts '#endif'
      puts "Generated: #{funcNumber - 1} functions in [ #{outHeader} ]\n\n"
    end
  end
  $totalFuncs += funcNumber - 1
end
puts 'End genaration'
puts "Total spinners: #{$totalFuncs}"
